import type { Metadata } from "next";
import { freePixelFont, supplyMediumFont } from "@/assets/fonts";
import Providers from "@/contexts/Providers";

import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "AFEL SLOT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${freePixelFont.className} ${supplyMediumFont.variable} antialiased container dark`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
